language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
env:
  global:
    secure: e2uoS842V/Uaaq311L3TxyPaJodmiDB6NsueZ2v9CSBhCavB1NCyDbJ3TLhSXrn0zlv4QQMLRM7hQAKzWnfIQzQrzUK1qCMOscJPbGvKr/RZRMxsIsAqJ+pDBqEkJOasfih4iaC6hkt0AvrLYn+WL4V7gyw0r0JJ77Okl/Jg5QU=
before_script: "cp config/database.yml.example config/database.yml"
